/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'PING_PONG_V1.2' 
 * Target:  'PING_PONG_V1.2' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32wlxx.h"



#endif /* RTE_COMPONENTS_H */
